# Codecov Configuration
# https://docs.codecov.com/docs/codecovyml-reference

coverage:
  # Coverage thresholds
  status:
    project:
      default:
        # Overall project coverage target
        target: 80%
        threshold: 2%
        if_ci_failed: error
    patch:
      default:
        # New code must have at least 80% coverage
        target: 80%
        threshold: 5%

  # Precision of coverage percentage (2 decimal places)
  precision: 2
  round: down
  range: "70...100"

# Parse configuration
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

# Comment configuration for PRs
comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

# Ignore certain paths
ignore:
  - "src/main/java/io/github/xmljim/Main.java"
  - "**/config/**"
  - "**/*Test.java"

# Flag management (optional - for future multi-module support)
flags:
  unit:
    paths:
      - src/main/java/
    carryforward: true
